# Generated by Django 3.0.8 on 2020-07-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeatherData',
            new_name='EnvironmentData',
        ),
        migrations.RenameField(
            model_name='environmentdata',
            old_name='temprature',
            new_name='temperature',
        ),
    ]
